# Generated by Django 5.0.6 on 2024-05-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                ("contributor_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("credential", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                ("number_of_verifications", models.IntegerField(blank=True, null=True)),
                ("number_of_contribution", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "contributor",
            },
        ),
        migrations.CreateModel(
            name="EmissionCategory",
            fields=[
                (
                    "emission_category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("category", models.CharField(max_length=255)),
                ("sub_category", models.TextField(blank=True, null=True)),
                ("lifecycle_activity", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "emissioncategory",
            },
        ),
        migrations.CreateModel(
            name="GeographicalScope",
            fields=[
                (
                    "geographical_scope_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("region", models.CharField(max_length=50)),
                ("contry", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "geographicalscope",
            },
        ),
        migrations.CreateModel(
            name="Datasource",
            fields=[
                ("data_sourceid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "reference_link",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "contributors",
                    models.ManyToManyField(
                        related_name="datasource", to="emissiondatabase.contributor"
                    ),
                ),
            ],
            options={
                "db_table": "datasource",
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("sector_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "geographic_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="emissiondatabase.geographicalscope",
                    ),
                ),
            ],
            options={
                "db_table": "sector",
            },
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "emission_factor_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("product_name", models.TextField(blank=True, null=True)),
                ("additional_information", models.TextField(blank=True, null=True)),
                (
                    "emission_quantity",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "emission_quantity_units",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pollutant", models.CharField(max_length=50)),
                (
                    "co2_or_co2_equivalent",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("technical_refrence", models.TextField(blank=True, null=True)),
                ("date_recorded", models.DateField(auto_now_add=True, null=True)),
                ("date_updated", models.DateField(auto_now=True, null=True)),
                (
                    "reliability_factor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("ef_tier", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emissionfactors_source",
                        to="emissiondatabase.datasource",
                    ),
                ),
                (
                    "emissioncategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emissionfactors_category",
                        to="emissiondatabase.emissioncategory",
                    ),
                ),
                (
                    "geographicalscope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emissionfactors_geography",
                        to="emissiondatabase.geographicalscope",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emissionfactors_sector",
                        to="emissiondatabase.sector",
                    ),
                ),
            ],
            options={
                "db_table": "emissionfactor",
            },
        ),
        migrations.CreateModel(
            name="JunctionContributorEmissionfactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emissiondatabase.contributor",
                    ),
                ),
                (
                    "emissionfactor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emissiondatabase.emissionfactor",
                    ),
                ),
            ],
            options={
                "db_table": "junction_contributor_emissionfactor",
                "unique_together": {("emissionfactor", "contributor")},
            },
        ),
    ]
